name: 'readmissions_demo'
version: '1.0'
config-version: 2

profile: 'readmissions_demo'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  readmissions_demo:
    staging:
      +materialized: view
    marts:
      +materialized: table
