version: 2

models:
  - name: fact_readmissions
    columns:
      - name: patient_id
        tests:
          - not_null

      - name: encounter_id
        tests:
          - not_null

      - name: is_30day_readmit
        description: "1 if the patient was readmitted within 30 days"
        tests:
          - accepted_values:
              arguments:
                values: [0, 1]
                quote: false

